### ISSUE TITLE
No such file or directory: 'savevars.pkl'

### ISSUE THREAD

**Issue by LULU-LULULA** [SSTato/YOLOv7_obb#9]
**Hello sir, I am getting the following error when using your code YOLOv7_obb_KFIOU, [Errno 2] No such file or directory: 'savevars.pkl', I looked at the code and found that the --mode parameter in train.py stores the CSL, KLD,KFIOU parameters, but I can't find savevars.pkl.  Can you give me some advice?**

```
root@autodl-container-3b34119352-a2e11eab:~#  python YOLOv7_obb_KFIOU-master/train.py
Traceback (most recent call last):
  File "YOLOv7_obb_KFIOU-master/train.py", line 27, in <module>
    import val  # for end-of-epoch mAP
  File "/root/YOLOv7_obb_KFIOU-master/val.py", line 19, in <module>
    from utils.rboxs_utils import poly2hbb, rbox2poly
  File "/root/YOLOv7_obb_KFIOU-master/utils/rboxs_utils.py", line 11, in <module>
    lmode = loadvar()
  File "/root/YOLOv7_obb_KFIOU-master/utils/optsave.py", line 13, in loadvar
    with open('savevars.pkl', 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'savevars.pkl'
```

**Comment by SSTato** [comment]
> YOLOv7_obb_KFIOU

YOLOv7_ obb_ KFIOU is not my code. You can ask the author of this code.
